## PyTorch fundamentals


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Intro to tensors

### Creating tensors

In [ ]:
# Creating a Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
torch.is_tensor(scalar)

True

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,7],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 7],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 7],
        [2, 4, 5]])

### RANDOM tensors
Why random tensors?

Important because neural networks start with tensors full of random numbers and adjust to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9479, 0.5262, 0.5744, 0.9777],
        [0.8465, 0.9823, 0.9367, 0.7815],
        [0.2494, 0.8048, 0.5496, 0.7363]])

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # Height, width, colour(RGB)
random_image_size_tensor

tensor([[[0.7805, 0.5514, 0.9748],
         [0.4877, 0.4398, 0.0303],
         [0.5227, 0.9861, 0.9826],
         ...,
         [0.4158, 0.1953, 0.5394],
         [0.6062, 0.8106, 0.0144],
         [0.4217, 0.7493, 0.2961]],

        [[0.8002, 0.3718, 0.7080],
         [0.2996, 0.8438, 0.6192],
         [0.9660, 0.9282, 0.9595],
         ...,
         [0.5096, 0.6417, 0.0289],
         [0.2878, 0.2701, 0.6517],
         [0.1736, 0.3985, 0.6224]],

        [[0.6608, 0.6873, 0.8061],
         [0.7995, 0.3646, 0.0103],
         [0.4287, 0.7103, 0.1210],
         ...,
         [0.5267, 0.6408, 0.6949],
         [0.6796, 0.3637, 0.0627],
         [0.1377, 0.6505, 0.7012]],

        ...,

        [[0.3987, 0.8434, 0.5034],
         [0.9119, 0.1989, 0.5276],
         [0.1532, 0.2601, 0.2433],
         ...,
         [0.2234, 0.9340, 0.7917],
         [0.4544, 0.8641, 0.1356],
         [0.7949, 0.3823, 0.8654]],

        [[0.0268, 0.9970, 0.7015],
         [0.1350, 0.2252, 0.4196],
         [0.

In [ ]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
random_image_size_tensor.ndim

3

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create the tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(ten_zeros)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32, # datatype
                                device="cpu", # where device is tensor on?
                               requires_grad=False) # need track gradient?
float_32_tensor.dtype

torch.float32

##### You can sacrifice precision for faster calculations or use more precisions (e.g. float64) if need more precision.

##### Datatypes errors:
1. Tensors not right datatype
2. Not right shape
3. Not right device

In [ ]:
# Change data type
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

### Getting information from tensors (attributes! no curly brackets unlike functions)
1. `tensor.dtype`
2. `tensor.shape`
3. `tensor.device`

In [ ]:
# Create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4384, 0.2647, 0.4054, 0.6873],
        [0.1221, 0.7884, 0.3770, 0.9410],
        [0.7694, 0.9701, 0.7195, 0.4131]])

In [ ]:
# Getting info
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.size()}") #OR some_tensor.shape
print(f"Device: {some_tensor.device}")

tensor([[0.4384, 0.2647, 0.4054, 0.6873],
        [0.1221, 0.7884, 0.3770, 0.9410],
        [0.7694, 0.9701, 0.7195, 0.4131]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Manipulating tensors

Tensor operations:
* Addition
* Subtraction
* Multiplication (element)
* Division
* Matrix multiplication

In [ ]:
# Create tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor - 5

tensor([-4, -3, -2])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor / 5

tensor([0.2000, 0.4000, 0.6000])

In [ ]:
# Try inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
torch.div(tensor, 2)

tensor([0.5000, 1.0000, 1.5000])

### Matrix multiplication
1. Element-wise
2. Matrix multiplication (dot product)

For matrix multiplications:
1. The inner dimensions must match
* `(3, 2) @ (3, 2)` wont work
* `(2, 3) @ (3, 2)` will work

2. The resulting matrix has the shape of the outer dimensions
* `(2, 3) @ (3, 2) gives matrix of shape (2, 2)`

In [ ]:
torch.rand(2,3) @ torch.rand(3,2)

tensor([[0.8304, 0.4203],
        [0.7372, 0.3777]])

In [ ]:
# Element-wise mult
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix mult
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix mult by hand
1 * 1 + 2 * 2 + 3 * 3


14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 606 µs, sys: 0 ns, total: 606 µs
Wall time: 672 µs


In [ ]:
# PyTorch's built-in matrix mult module is faster
%%time
torch.matmul(tensor,tensor)

CPU times: user 30 µs, sys: 5 µs, total: 35 µs
Wall time: 38.1 µs


tensor(14)

### Shape errors

In [ ]:
# Shapes for matrix mult
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B) # torch.mm is alias for torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate shape of one of the tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensors


In [ ]:
tensor_B, tensor_B.shape


In [ ]:
# Transpose
tensor_B.T, tensor_B.T.shape

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

In [ ]:
torch.matmul(tensor_A, tensor_B.T).shape

## Finding the min, max, mean, sum etc (tensor aggregation)

In [ ]:
# Create tensor
x = torch.arange(1, 100, 10)
x, x.dtype

In [ ]:
# min
x.min(), torch.min(x)

In [ ]:
# max
x.max(), torch.max(x)

In [ ]:
# mean -> need change int dtype to float for mean
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

In [ ]:
#sum
x.sum(), torch.sum(x)

## Finding positional min and max


In [ ]:
x


In [ ]:
# Find the position index in tensor that has the min value with argmin
x.argmin()

In [ ]:
x.argmax()

In [ ]:
x[0]

In [ ]:
x[9]

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but
keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or beside (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted in a certain way

In [ ]:
# Creating a tensor
import torch

x = torch.arange(1.,10.)
x, x.shape

In [ ]:
# Reshape to add an extra dimension (number of elements must match)
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

In [ ]:
# Changing z changes x because a view of a tensor shares same memory as the input
z[:, 0] = 5
z, x

In [ ]:
# Stacking tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked


In [ ]:
# vstack (vertical stack)
x_vstack = torch.vstack([x,x,x,x])
x_vstack


In [ ]:
# hstack (horizontal stack)
x_hstack = torch.hstack([x,x,x,x])
x_hstack

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
tensor = torch.tensor([[[1,2], [3,4]]])

In [ ]:
tensor.shape

In [ ]:
tensor = torch.squeeze(tensor) # Or tensor.squeeze()
tensor

In [ ]:
tensor.shape

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
tensor = torch.tensor([1,2,3,4])
tensor

In [ ]:
torch.unsqueeze(tensor, 0) # adding to 0th dim

In [ ]:
torch.unsqueeze(tensor, 0).shape


In [ ]:
torch.unsqueeze(tensor, 1) # adding to 1st dim

In [ ]:
torch.unsqueeze(tensor, 1).shape

In [ ]:
# torch.permute - rearranges the dimensions of the target tensor in a particular order
x = torch.rand(size=(224,224,3)) # height, width, colour channels for image tensor
x

In [ ]:
x.shape

In [ ]:
x_permuted = x.permute(2, 0, 1) # shifts axis 0->1, 1-->2, 2-->3
x_permuted.shape # channels, height, width now

In [ ]:
x_permuted


### Indexing (selecting data from tensors)

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x

In [ ]:
# Indexing
x[0]

In [ ]:
# Indexing on middle bracket (dim=1)
x[0][0]

In [ ]:
x[0, 0]

In [ ]:
# Now dim = 2
x[0][0][0]

In [ ]:
x[0][0][1]

In [ ]:
x[0][1][1]

In [ ]:
x[0][2][2]

In [ ]:
# Can use : to select all of a target dimension
x[:, 0]

In [ ]:
 # Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
 x[:, :, 1]

In [ ]:
x[:, 1, 1]

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

In [ ]:
x[:, :, 2]

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`

* PyTorch tensor to NumPy -> `torch.Tensor.numpy()`


In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

### PyTorch default datatype is float32 but np datatype default is float64

In [ ]:
# Change value of array, what happens to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor # This time numpy dtype follows pytorch's default

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short, how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to make them better representations -> again -> again...`

To reduce randomness, concept of random seed.

Random seed flavour the randomness

In [ ]:
import torch

# Create 2 random tensors
A = torch.rand(3, 4)
B = torch.rand(3, 4)

print(A)
print(B)

tensor([[0.9532, 0.3838, 0.0757, 0.9424],
        [0.8077, 0.6277, 0.3088, 0.8091],
        [0.0686, 0.3313, 0.7076, 0.7681]])
tensor([[0.4865, 0.5224, 0.4710, 0.0952],
        [0.1292, 0.3707, 0.0759, 0.3094],
        [0.5507, 0.6018, 0.4725, 0.4179]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set random seed
RANDOM_SEED = 42 # seed only works for one block of code
torch.manual_seed(RANDOM_SEED)
C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # repeat
D = torch.rand(3,4)

print(C)
print(D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


## Running tensors and PyTorch objects on the GPUs

GPUs = faster computation on numbers, CUDA, NVIDIA hardware, PyTorch behind the scenes


### Getting a GPU

1. Use Google CoLab for a free GPU
2. Use your own GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud

For 2, 3: There is a little bit of setting up, refer to PyTorch documentation

In [ ]:
# Check GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count devices
torch.cuda.device_count()

1

In [ ]:
!nvidia-smi

Tue Jan 16 12:06:38 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Putting tensors (and models) on the GPU

We want our tensor/models on the GPU so that we have faster computations

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Moving to the target device e.g. GPU
tensor_on_gpu = tensor.to(device) #this will work even if no GPU (due to device-agnostic code)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Move tensors back to CPU (e.g. NumPy only can use CPU)


In [ ]:
tensor_on_gpu.numpy() # Device issues

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_on_cpu = tensor_on_gpu.to("cpu")

In [ ]:
tensor_on_cpu.numpy()

array([1, 2, 3])

### EXERCISES

In [ ]:
#Q2
tensor = torch.rand(7, 7)
tensor

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]])

In [ ]:
#Q3
tensor_2 = torch.rand(1, 7)
tensor_2

tensor([[0.0600, 0.2846, 0.2007, 0.5014, 0.3139, 0.4654, 0.1612]])

In [ ]:
tensor_2.T

tensor([[0.0600],
        [0.2846],
        [0.2007],
        [0.5014],
        [0.3139],
        [0.4654],
        [0.1612]])

In [ ]:
torch.matmul(tensor, tensor_2.T)

tensor([[1.1717],
        [0.9437],
        [0.9601],
        [0.8217],
        [1.0516],
        [0.6525],
        [0.3525]])

In [ ]:
#Q4
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(7, 7)
tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [ ]:
torch.manual_seed(0)
tensor_2 = torch.rand(1, 7)
tensor_2

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [ ]:
torch.matmul(tensor, tensor_2.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [ ]:
#Q5
torch.cuda.manual_seed(1234)

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

torch.cuda.manual_seed(1234)
A = torch.rand(2, 3).to(device)

torch.cuda.manual_seed(1234)
B = torch.rand(2, 3).to(device)

A, B

(tensor([[0.0332, 0.1387, 0.2422],
         [0.8155, 0.7932, 0.2783]], device='cuda:0'),
 tensor([[0.4820, 0.8198, 0.9971],
         [0.6984, 0.5675, 0.8352]], device='cuda:0'))

In [ ]:
torch.cuda.manual_seed(1234)
A = torch.rand(2, 3).to(device)
A

tensor([[0.7011, 0.2038, 0.6511],
        [0.7745, 0.4369, 0.5191]], device='cuda:0')

In [ ]:
#Q10

torch.manual_seed(7)

A = torch.rand(1, 1, 1, 10)

A= A.squeeze()
A.shape

torch.Size([10])